apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: query-killer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: query-killer
    spec:
      containers:
      - name: query-killer
        image: {{ .Values.queryKiller.image.name }}:{{ .Values.queryKiller.image.tag }}
        env:
          - name: MYSQL_HOST
            value: {{ .Values.mysql.host | quote }}
          - name: MYSQL_USERNAME
            value: {{ .Values.mysql.username | quote }}
          - name: MYSQL_PASSWORD
            value: {{ .Values.mysql.password | quote }}
          - name: MAX_QUERY_TIME
            value: {{ .Values.queryKiller.maxQueryTime | quote }}
        resources:
{{ toYaml .Values.queryKiller.resources | indent 12 }}
